/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.uvic.seng330.ex5;
import java.io.IOException;
import java.util.Date;
import java.util.Optional;

public class Driver {

    public static void main(String[] args) throws IOException {

        WhaleMonitoringSystem wms = new WhaleMonitoringSystem();

        Location vic = new Location(-123.3656, 48.4284);
        Weather weather = new Weather(vic);
        System.out.println("Victoria current minimum temperature: " + weather.getTempMin() + " degrees celsius.");
        System.out.println("Victoria current maximum temperature: " + weather.getTempMax() + " degrees celsius.");
        System.out.println("Victoria current visibility: " + weather.getVisibility() + " meters.");
        Reporter Keenan = wms.addReporter("Keenan");
        Whale Whale01 = wms.addWhale(Whale.Gender.MALE, Whale.Breed.BLUE, true, 600, 20);
        //Date(int year, int month, int date, int hrs, int min)

        Observation obs = wms.addObservation(Keenan, Whale01,new Location(32, 45), new Date(2020,9,25,8,58));

        // Date.Month.Sep, 25, "8:58", "PDT", 2020)
        Observation obs2 = wms.addObservation(Keenan,Whale01,new Location(55,45), new Date(2020,9,25,8,22));

        Optional <Observation> obsF = wms.getObservationCatalog().searchByLocation(55,44);
        if(obsF.isPresent())
            System.out.println(obsF.toString());
    }
}